name: CI Pipeline

on:
  # Trigger on pull requests to main
  pull_request:
    branches: [main]
  # Also trigger on direct pushes to main
  push:
    branches: [main]

jobs:
  # First job: Verify code quality
  verify-and-build:
    name: "Verify & Build"

    # Run on Ubuntu virtual machine
    runs-on: ubuntu-latest

    # Environment variables for all steps in this job
    env:
      NODE_ENV: test
      CI: true

    steps:
      # Step 1: Get code from repository
      - name: "Checkout repository"
        uses: actions/checkout@v4

      # Step 2: Setup Node.js environment
      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      # Step 3: Install dependencies
      - name: "Install dependencies"
        run: npm ci

      # Step 4: Code linting
      - name: "Lint code"
        run: npm run lint
        continue-on-error: false # Fail pipeline if linting fails

      # Step 5: Type checking
      - name: "TypeScript check"
        run: npx tsc --noEmit

      # Step 6: Build verification
      - name: "Build project"
        run: npm run build

  # Second job: Security and dependency scanning
  security-scan:
    name: "Security Scan"
    runs-on: ubuntu-latest
    needs: verify-and-build # Wait for first job to complete
    if: ${{ github.event_name == 'pull_request' }} # Only run on PRs

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: "Install dependencies"
        run: npm ci

      - name: "Run npm audit"
        run: npm audit --audit-level moderate
        continue-on-error: true

      - name: "Run Trivy vulnerability scanner"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "sarif"
          output: "trivy-results.sarif"

      - name: "Upload Trivy scan results to GitHub Security tab"
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  # Third job: Build and deploy preview (for PRs)
  preview-deploy:
    name: "Preview Deploy"
    runs-on: ubuntu-latest
    needs: verify-and-build
    if: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: "Install dependencies"
        run: npm ci

      - name: "Install Vercel CLI"
        run: npm install -g vercel

      - name: "Pull Vercel environment variables"
        run: vercel pull --yes --environment=production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: "Build for preview"
        run: npm run build:dev

      - name: "Deploy to Vercel"
        run: vercel --prod=false --yes
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
